version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace
    volumes:
      - .:/workspace
    ports:
      - "3000:3000"
    command: sh -c "cd apps/web && npm run dev"
    depends_on:
      - backend

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    working_dir: /app
