version: "3.9"

services:
  web:
    build:
      context: ./apps/web
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app
    working_dir: /app
    command: pnpm dev

  backend:
    build:
      context: ./apps/backend
    ports:
      - "5000:5000"
    volumes:
      - ./apps/backend:/src
    working_dir: /src/TecoApi
    command: dotnet watch run
