services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./apps/backend:/src:delegated
      - nuget_packages:/root/.nuget/packages
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://0.0.0.0:5000"
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
    working_dir: /src/TecoApi
    env_file:
      - ./.env
    command: dotnet watch run --urls "http://0.0.0.0:5000"

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app:delegated
      - web_node_modules:/app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://backend:5000
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      CI: "true"
    working_dir: /app
    command: ["sh", "-c", "pnpm exec next dev -H 0.0.0.0 -p 3000"]
    depends_on:
      - backend

volumes:
  nuget_packages: {}
  web_node_modules: {}