CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE TABLE "Addresses" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Street" character varying(100) NOT NULL,
        "Number" character varying(10),
        "Complement" character varying(100),
        "Neighborhood" character varying(100) NOT NULL,
        "City" character varying(100) NOT NULL,
        "State" character varying(100) NOT NULL,
        "PostalCode" character varying(9) NOT NULL,
        CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CPF" character varying(11),
        "CNPJ" character varying(14),
        "Email" text NOT NULL,
        "Password" text NOT NULL,
        "Name" text NOT NULL,
        "Role" text NOT NULL,
        "PersonalAddressId" bigint,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Users_Addresses_PersonalAddressId" FOREIGN KEY ("PersonalAddressId") REFERENCES "Addresses" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE TABLE "Providers" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" bigint NOT NULL,
        "Bio" character varying(500) NOT NULL,
        "Skills" text[] NOT NULL,
        "WorkAddressId" bigint,
        "PriceBase" real,
        CONSTRAINT "PK_Providers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Providers_Addresses_WorkAddressId" FOREIGN KEY ("WorkAddressId") REFERENCES "Addresses" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Providers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE TABLE "Requesters" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" bigint NOT NULL,
        CONSTRAINT "PK_Requesters" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Requesters_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE TABLE "Requests" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RequesterId" bigint NOT NULL,
        "Title" character varying(100) NOT NULL,
        "Description" character varying(1000) NOT NULL,
        "Photos" text[] NOT NULL,
        "Status" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ServiceAddressId" bigint,
        CONSTRAINT "PK_Requests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Requests_Addresses_ServiceAddressId" FOREIGN KEY ("ServiceAddressId") REFERENCES "Addresses" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Requests_Requesters_RequesterId" FOREIGN KEY ("RequesterId") REFERENCES "Requesters" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE TABLE "Proposals" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RequestId" bigint NOT NULL,
        "ProviderId" bigint NOT NULL,
        "Amount" numeric NOT NULL,
        "Message" character varying(500) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Proposals" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Proposals_Providers_ProviderId" FOREIGN KEY ("ProviderId") REFERENCES "Providers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Proposals_Requests_RequestId" FOREIGN KEY ("RequestId") REFERENCES "Requests" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE TABLE "Orders" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ProposalId" bigint NOT NULL,
        "Status" text NOT NULL,
        "PaymentStatus" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "StartedAt" timestamp with time zone,
        "FinishedAt" timestamp with time zone,
        "ClientConfirmed" boolean NOT NULL,
        "ProviderId" bigint,
        "RequesterId" bigint,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Orders_Proposals_ProposalId" FOREIGN KEY ("ProposalId") REFERENCES "Proposals" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Orders_Providers_ProviderId" FOREIGN KEY ("ProviderId") REFERENCES "Providers" ("Id"),
        CONSTRAINT "FK_Orders_Requesters_RequesterId" FOREIGN KEY ("RequesterId") REFERENCES "Requesters" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE TABLE "Reviews" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" bigint NOT NULL,
        "ProviderId" bigint NOT NULL,
        "RequesterId" bigint NOT NULL,
        "Rating" integer NOT NULL,
        "Comment" character varying(500) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Reviews_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Reviews_Providers_ProviderId" FOREIGN KEY ("ProviderId") REFERENCES "Providers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Reviews_Requesters_RequesterId" FOREIGN KEY ("RequesterId") REFERENCES "Requesters" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Orders_ProposalId" ON "Orders" ("ProposalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE INDEX "IX_Orders_ProviderId" ON "Orders" ("ProviderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE INDEX "IX_Orders_RequesterId" ON "Orders" ("RequesterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE INDEX "IX_Proposals_ProviderId" ON "Proposals" ("ProviderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE INDEX "IX_Proposals_RequestId" ON "Proposals" ("RequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Providers_UserId" ON "Providers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Providers_WorkAddressId" ON "Providers" ("WorkAddressId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Requesters_UserId" ON "Requesters" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE INDEX "IX_Requests_RequesterId" ON "Requests" ("RequesterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Requests_ServiceAddressId" ON "Requests" ("ServiceAddressId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Reviews_OrderId" ON "Reviews" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE INDEX "IX_Reviews_ProviderId" ON "Reviews" ("ProviderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE INDEX "IX_Reviews_RequesterId" ON "Reviews" ("RequesterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_PersonalAddressId" ON "Users" ("PersonalAddressId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251011142837_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251011142837_InitialCreate', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013204826_ChatMessageMigration') THEN
    ALTER TABLE "Proposals" ADD "ChatMessageId" bigint;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013204826_ChatMessageMigration') THEN
    CREATE TABLE "ChatMessages" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RequestId" bigint NOT NULL,
        "SenderId" bigint NOT NULL,
        "Content" character varying(100) NOT NULL,
        "IsProposal" boolean NOT NULL,
        "ProposalId" bigint,
        "SentAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ChatMessages_Requests_RequestId" FOREIGN KEY ("RequestId") REFERENCES "Requests" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ChatMessages_Users_SenderId" FOREIGN KEY ("SenderId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013204826_ChatMessageMigration') THEN
    CREATE UNIQUE INDEX "IX_Proposals_ChatMessageId" ON "Proposals" ("ChatMessageId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013204826_ChatMessageMigration') THEN
    CREATE INDEX "IX_ChatMessages_RequestId" ON "ChatMessages" ("RequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013204826_ChatMessageMigration') THEN
    CREATE INDEX "IX_ChatMessages_SenderId" ON "ChatMessages" ("SenderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013204826_ChatMessageMigration') THEN
    ALTER TABLE "Proposals" ADD CONSTRAINT "FK_Proposals_ChatMessages_ChatMessageId" FOREIGN KEY ("ChatMessageId") REFERENCES "ChatMessages" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251013204826_ChatMessageMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251013204826_ChatMessageMigration', '9.0.9');
    END IF;
END $EF$;
COMMIT;

