DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'core_schema') THEN
        CREATE SCHEMA core_schema;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS core_schema."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'core_schema') THEN
            CREATE SCHEMA core_schema;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE TABLE core_schema."Addresses" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Street" character varying(100) NOT NULL,
        "Number" character varying(10),
        "Complement" character varying(100),
        "Neighborhood" character varying(100) NOT NULL,
        "City" character varying(100) NOT NULL,
        "State" character varying(100) NOT NULL,
        "PostalCode" character varying(9) NOT NULL,
        CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE TABLE core_schema."Users" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CPF" character varying(11),
        "CNPJ" character varying(14),
        "Email" text NOT NULL,
        "Password" text NOT NULL,
        "Name" text NOT NULL,
        "Role" text NOT NULL,
        "PersonalAddressId" bigint,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Users_Addresses_PersonalAddressId" FOREIGN KEY ("PersonalAddressId") REFERENCES core_schema."Addresses" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE TABLE core_schema."Providers" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" bigint NOT NULL,
        "Bio" character varying(500) NOT NULL,
        "Skills" text[] NOT NULL,
        "WorkAddressId" bigint,
        "PriceBase" real,
        CONSTRAINT "PK_Providers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Providers_Addresses_WorkAddressId" FOREIGN KEY ("WorkAddressId") REFERENCES core_schema."Addresses" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Providers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES core_schema."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE TABLE core_schema."Requesters" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" bigint NOT NULL,
        CONSTRAINT "PK_Requesters" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Requesters_Users_UserId" FOREIGN KEY ("UserId") REFERENCES core_schema."Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE TABLE core_schema."Requests" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RequesterId" bigint NOT NULL,
        "Title" character varying(100) NOT NULL,
        "Description" character varying(1000) NOT NULL,
        "Photos" text[] NOT NULL,
        "Status" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "ServiceAddressId" bigint,
        CONSTRAINT "PK_Requests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Requests_Addresses_ServiceAddressId" FOREIGN KEY ("ServiceAddressId") REFERENCES core_schema."Addresses" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_Requests_Requesters_RequesterId" FOREIGN KEY ("RequesterId") REFERENCES core_schema."Requesters" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE TABLE core_schema."Proposals" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RequestId" bigint NOT NULL,
        "ProviderId" bigint NOT NULL,
        "Amount" numeric NOT NULL,
        "Message" character varying(500) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Proposals" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Proposals_Providers_ProviderId" FOREIGN KEY ("ProviderId") REFERENCES core_schema."Providers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Proposals_Requests_RequestId" FOREIGN KEY ("RequestId") REFERENCES core_schema."Requests" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE TABLE core_schema."Orders" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ProposalId" bigint NOT NULL,
        "Status" text NOT NULL,
        "PaymentStatus" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "StartedAt" timestamp with time zone,
        "FinishedAt" timestamp with time zone,
        "ClientConfirmed" boolean NOT NULL,
        "ProviderId" bigint,
        "RequesterId" bigint,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Orders_Proposals_ProposalId" FOREIGN KEY ("ProposalId") REFERENCES core_schema."Proposals" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Orders_Providers_ProviderId" FOREIGN KEY ("ProviderId") REFERENCES core_schema."Providers" ("Id"),
        CONSTRAINT "FK_Orders_Requesters_RequesterId" FOREIGN KEY ("RequesterId") REFERENCES core_schema."Requesters" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE TABLE core_schema."Reviews" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" bigint NOT NULL,
        "ProviderId" bigint NOT NULL,
        "RequesterId" bigint NOT NULL,
        "Rating" integer NOT NULL,
        "Comment" character varying(500) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Reviews_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES core_schema."Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Reviews_Providers_ProviderId" FOREIGN KEY ("ProviderId") REFERENCES core_schema."Providers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Reviews_Requesters_RequesterId" FOREIGN KEY ("RequesterId") REFERENCES core_schema."Requesters" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Orders_ProposalId" ON core_schema."Orders" ("ProposalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE INDEX "IX_Orders_ProviderId" ON core_schema."Orders" ("ProviderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE INDEX "IX_Orders_RequesterId" ON core_schema."Orders" ("RequesterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE INDEX "IX_Proposals_ProviderId" ON core_schema."Proposals" ("ProviderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE INDEX "IX_Proposals_RequestId" ON core_schema."Proposals" ("RequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Providers_UserId" ON core_schema."Providers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Providers_WorkAddressId" ON core_schema."Providers" ("WorkAddressId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Requesters_UserId" ON core_schema."Requesters" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE INDEX "IX_Requests_RequesterId" ON core_schema."Requests" ("RequesterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Requests_ServiceAddressId" ON core_schema."Requests" ("ServiceAddressId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Reviews_OrderId" ON core_schema."Reviews" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE INDEX "IX_Reviews_ProviderId" ON core_schema."Reviews" ("ProviderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE INDEX "IX_Reviews_RequesterId" ON core_schema."Reviews" ("RequesterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Users_PersonalAddressId" ON core_schema."Users" ("PersonalAddressId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM core_schema."__EFMigrationsHistory" WHERE "MigrationId" = '20251010124115_InitialCreate') THEN
    INSERT INTO core_schema."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251010124115_InitialCreate', '9.0.9');
    END IF;
END $EF$;
COMMIT;

